<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace />
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.1</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>SeongSikChae</Authors>
    <Description>.NET System.Configuration namespace Extensions</Description>
    <RepositoryUrl>https://github.com/SeongSikChae/System.Configuration.Extensions.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/SeongSikChae/System.Configuration.Extensions.git</PackageProjectUrl>
  </PropertyGroup>

</Project>
