<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace />
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>1.0.1</Version>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>SeongSikChae</Authors>
		<Description>.NET System.Configuration namespace Extensions</Description>
		<RepositoryUrl>https://github.com/SeongSikChae/System.Configuration.Extensions.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/SeongSikChae/System.Configuration.Extensions.git</PackageProjectUrl>
		<AssemblyName>Biz.Bizadm.$(MSBuildProjectName)</AssemblyName>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
